### ISSUE TITLE
ljust not defined for template

### ISSUE THREAD

**Issue by psychonaut** [express42-cookbooks/postgresql_lwrp#36]
I've tried to use this module with the simplest configuration and I've got error during run:

```
Chef::Mixin::Template::TemplateError (undefined method `ljust' for nil:NilClass) on line #9:
  7: 
  8: <% @configuration.each do |config| %>
  9: <%= "#{config[:type].ljust(7)} #{config[:database].ljust(15)} #{config[:user].ljust(15)} #{config[:address].ljust(23)} #{config[:method]}"%>
 10: <% end %>

  (erubis):9:in `block (2 levels) in evaluate'
  (erubis):8:in `each'
  (erubis):8:in `block in evaluate'
  /usr/lib/ruby/vendor_ruby/erubis/evaluator.rb:74:in `instance_eval'
  /usr/lib/ruby/vendor_ruby/erubis/evaluator.rb:74:in `evaluate'
  /usr/lib/ruby/vendor_ruby/chef/mixin/template.rb:161:in `_render_template'
  /usr/lib/ruby/vendor_ruby/chef/mixin/template.rb:147:in `render_template'
  /usr/lib/ruby/vendor_ruby/chef/provider/template/content.rb:53:in `file_for_provider'
  /usr/lib/ruby/vendor_ruby/chef/file_content_management/content_base.rb:40:in `tempfile'
  /usr/lib/ruby/vendor_ruby/chef/provider/file.rb:462:in `tempfile'
  /usr/lib/ruby/vendor_ruby/chef/provider/file.rb:339:in `do_generate_content'
  /usr/lib/ruby/vendor_ruby/chef/provider/file.rb:150:in `action_create'
  /usr/lib/ruby/vendor_ruby/chef/provider.rb:145:in `run_action'
  /usr/lib/ruby/vendor_ruby/chef/resource.rb:596:in `run_action'
  /usr/lib/ruby/vendor_ruby/chef/runner.rb:69:in `run_action'
  /usr/lib/ruby/vendor_ruby/chef/runner.rb:97:in `block (2 levels) in converge'
  /usr/lib/ruby/vendor_ruby/chef/runner.rb:97:in `each'
  /usr/lib/ruby/vendor_ruby/chef/runner.rb:97:in `block in converge'
  /usr/lib/ruby/vendor_ruby/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
  /usr/lib/ruby/vendor_ruby/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
  /usr/lib/ruby/vendor_ruby/chef/resource_collection/stepable_iterator.rb:85:in `step'
  /usr/lib/ruby/vendor_ruby/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
  /usr/lib/ruby/vendor_ruby/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  /usr/lib/ruby/vendor_ruby/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
  /usr/lib/ruby/2.3.0/forwardable.rb:189:in `execute_each_resource'
  /usr/lib/ruby/vendor_ruby/chef/runner.rb:96:in `converge'
  /usr/lib/ruby/vendor_ruby/chef/provider.rb:362:in `compile_and_converge_action'
  (eval):2:in `action_create'
  /usr/lib/ruby/vendor_ruby/chef/provider.rb:145:in `run_action'
  /usr/lib/ruby/vendor_ruby/chef/resource.rb:596:in `run_action'
  /usr/lib/ruby/vendor_ruby/chef/runner.rb:69:in `run_action'
  /usr/lib/ruby/vendor_ruby/chef/runner.rb:97:in `block (2 levels) in converge'
  /usr/lib/ruby/vendor_ruby/chef/runner.rb:97:in `each'
  /usr/lib/ruby/vendor_ruby/chef/runner.rb:97:in `block in converge'
  /usr/lib/ruby/vendor_ruby/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
  /usr/lib/ruby/vendor_ruby/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
  /usr/lib/ruby/vendor_ruby/chef/resource_collection/stepable_iterator.rb:85:in `step'
  /usr/lib/ruby/vendor_ruby/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
  /usr/lib/ruby/vendor_ruby/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  /usr/lib/ruby/vendor_ruby/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
  /usr/lib/ruby/2.3.0/forwardable.rb:189:in `execute_each_resource'
  /usr/lib/ruby/vendor_ruby/chef/runner.rb:96:in `converge'
  /usr/lib/ruby/vendor_ruby/chef/client.rb:667:in `block in converge'
  /usr/lib/ruby/vendor_ruby/chef/client.rb:662:in `catch'
  /usr/lib/ruby/vendor_ruby/chef/client.rb:662:in `converge'
  /usr/lib/ruby/vendor_ruby/chef/client.rb:701:in `converge_and_save'
  /usr/lib/ruby/vendor_ruby/chef/client.rb:281:in `run'
  /usr/lib/ruby/vendor_ruby/chef/application.rb:285:in `block in fork_chef_client'
  /usr/lib/ruby/vendor_ruby/chef/application.rb:273:in `fork'
  /usr/lib/ruby/vendor_ruby/chef/application.rb:273:in `fork_chef_client'
  /usr/lib/ruby/vendor_ruby/chef/application.rb:238:in `block in run_chef_client'
  /usr/lib/ruby/vendor_ruby/chef/local_mode.rb:44:in `with_server_connectivity'
  /usr/lib/ruby/vendor_ruby/chef/application.rb:226:in `run_chef_client'
  /usr/lib/ruby/vendor_ruby/chef/application/client.rb:456:in `sleep_then_run_chef_client'
  /usr/lib/ruby/vendor_ruby/chef/application/client.rb:443:in `block in interval_run_chef_client'
  /usr/lib/ruby/vendor_ruby/chef/application/client.rb:442:in `loop'
  /usr/lib/ruby/vendor_ruby/chef/application/client.rb:442:in `interval_run_chef_client'
  /usr/lib/ruby/vendor_ruby/chef/application/client.rb:426:in `run_application'
  /usr/lib/ruby/vendor_ruby/chef/application.rb:58:in `run'
  /usr/bin/chef-client:26:in `<main>'

```

Do you know maybe what I am missing.

```
 root@ustaw:~# chef-client --version
Chef: 12.10.24
```

**Comment by strangeman** [comment]
Looks like you're not filled one of these variables: 
`config[:type]` or `config[:database]` or `config[:user]` or  `config[:address]`, and `ljust` tried to apply to non-existent variable.

Can you show your `hba_configuration` array?

**Comment by psychonaut** [comment]
i've converting cookbook from hw-postgresql, so i've got :db instead of :database. My bad. Thnx for response.
